name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    environment: default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build Windows binary
        run: go build -ldflags "-H=windowsgui" -o led-screen-sync.exe
        
      - name: Verify binary exists
        run: |
          if (Test-Path "led-screen-sync.exe") {
            Write-Host "Binary found: $(Get-Item led-screen-sync.exe | Select-Object Name, Length)"
            Get-FileHash led-screen-sync.exe
          } else {
            Write-Host "ERROR: Binary not found!"
            exit 1
          }
        
      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: led-screen-sync.exe
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Scan with VirusTotal
        uses: crazy-max/ghaction-virustotal@v4
        id: virustotal
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: led-screen-sync.exe
          
      - name: Add VirusTotal scan result to release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const releaseId = context.payload.release.id;
            
            // Get current release
            const release = await github.rest.repos.getRelease({
              owner,
              repo,
              release_id: releaseId
            });
            
            // Add VirusTotal scan link to release body
            const vtLink = `\n\n🛡️ **Security Scan**: [VirusTotal Report](${{ steps.virustotal.outputs.analysis }})`;
            const updatedBody = release.data.body + vtLink;
            
            // Update release with VirusTotal link
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id: releaseId,
              body: updatedBody
            });
