name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  build:
    runs-on: windows-latest
    environment: default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Install dependencies
        run: go mod download

      - name: Build Windows binary
        run: |
          mkdir bin
          go build -ldflags "-H=windowsgui" -o bin/led-screen-sync.exe

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            bin/led-screen-sync.exe
        
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/led-screen-sync.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
