name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  build:
    runs-on: windows-latest
    environment: default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Install dependencies
        run: go mod download

      - name: Build Windows binary
        run: |
          $VERSION = "${{ github.ref_name }}"
          $COMMIT = "${{ github.sha }}"
          $DATE = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"
          
          go build -ldflags "-H=windowsgui -X main.version=$VERSION -X main.commit=$COMMIT -X main.date=$DATE" -o led-screen-sync.exe

      - name: Prepare release zip
        run: |
          cp led-screen-sync.example.yaml led-screen-sync.yaml
          zip led-screen-sync.zip led-screen-sync.exe led-screen-sync.yaml README.md

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            led-screen-sync.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Sleep for 10 seconds
        run: Start-Sleep -Seconds 10 

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            led-screen-sync.exe
