name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  virustotal:
    runs-on: ubuntu-latest
    environment: default
    permissions:
      # required to write GitHub Release body
      contents: write
    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            ./bin/led-screen-sync.exe/led-screen-sync.exe
